.PHONY: clean All

All:
	@echo "----------Building project:[ laba1_1 - Debug ]----------"
	@cd "C++Projects2" && "$(MAKE)" -f  "laba1_1.mk"
clean:
	@echo "----------Cleaning project:[ laba1_1 - Debug ]----------"
	@cd "C++Projects2" && "$(MAKE)" -f  "laba1_1.mk" clean
